// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TrackerRPC.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace TrackerRPC {
  public static partial class dbUpdate
  {
    static readonly string __ServiceName = "TrackerRPC.dbUpdate";

    static readonly grpc::Marshaller<global::TrackerRPC.UpdateRequest> __Marshaller_UpdateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TrackerRPC.UpdateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TrackerRPC.RecieptConfirmation> __Marshaller_RecieptConfirmation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TrackerRPC.RecieptConfirmation.Parser.ParseFrom);

    static readonly grpc::Method<global::TrackerRPC.UpdateRequest, global::TrackerRPC.RecieptConfirmation> __Method_GetRow = new grpc::Method<global::TrackerRPC.UpdateRequest, global::TrackerRPC.RecieptConfirmation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRow",
        __Marshaller_UpdateRequest,
        __Marshaller_RecieptConfirmation);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TrackerRPC.TrackerRPCReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of dbUpdate</summary>
    public abstract partial class dbUpdateBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TrackerRPC.RecieptConfirmation> GetRow(global::TrackerRPC.UpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for dbUpdate</summary>
    public partial class dbUpdateClient : grpc::ClientBase<dbUpdateClient>
    {
      /// <summary>Creates a new client for dbUpdate</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public dbUpdateClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for dbUpdate that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public dbUpdateClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected dbUpdateClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected dbUpdateClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TrackerRPC.RecieptConfirmation GetRow(global::TrackerRPC.UpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRow(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TrackerRPC.RecieptConfirmation GetRow(global::TrackerRPC.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRow, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TrackerRPC.RecieptConfirmation> GetRowAsync(global::TrackerRPC.UpdateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRowAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TrackerRPC.RecieptConfirmation> GetRowAsync(global::TrackerRPC.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRow, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override dbUpdateClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new dbUpdateClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(dbUpdateBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRow, serviceImpl.GetRow).Build();
    }

  }
}
#endregion
